- hosts: common
  become: "{{ sudo | default('yes') }}"
  roles:
    - mikysal78.ninux_common
    - mikysal78.ansible_iptables
    - mikysal78.ansible_fail2ban
  vars:
    # common
    ninux_common_ipv4_forward: 1
    ninux_common_ssh_port: 2400
    # variabili per ruolo common
    users:
      - name: michele
        authorized:
          - ./keys/michele.pub
      - name: nino
        authorized:
          - ./keys/nino.pub
      - name: marco
        authorized:
          - ./keys/hispanico.pub
      - name: federico
        authorized:
          - ./keys/federico-1.pub
          - ./keys/federico-2.pub
    ssh_port: 2400
    mail_admin: mikysal78@gmail.com

