- hosts: dns_server
  become: "{{ sudo | default('yes') }}"
  roles:
    - bind
  tags:
    - bind-server
  vars:
    bind_listen_ipv4:
      - 127.0.0.1
      - 10.27.253.1
      - 10.27.253.2
    bind_zone_master_server_ip: 10.27.253.1
  pre_tasks:
    - name: Get dict for each zone
      include_vars:
        dir: zones
    - name: Merge zone dicts
      set_fact:
        bind_zone_domains:
          "{{ basilicata_nnxx }} +
           {{ router_nnxx }}"

