- hosts: dns-server
  become: "{{ sudo | default('yes') }}"
  roles:
    - common
    - vpnbas
    - olsrd2
    - bind
  vars:
    # common
    common_ipv4_forward: 1
    common_ssh_port: 2400
    # variabili per ruolo common
    users:
      - name: michele
        authorized:
          - ./keys/michele.pub
      - name: nino
        authorized:
          - ./keys/nino.pub
      - name: marco
        authorized:
          - ./keys/hispanico.pub
      - name: federico
        authorized:
          - ./keys/federico-1.pub
          - ./keys/federico-2.pub
    # User e Pass for Auth OpenVPN
    vpnuser: "{{ inventory_hostname }}"
    vpnpass: n1nuxb4sm4n4g3mentvpn
    # OLSR interfaces
    olsrd2_interfaces:
      - vpnbas
    # bind
    bind_listen_ipv4:
      - 127.0.0.1
      - 10.27.253.10
      - 10.27.253.11
      - 176.9.204.50
      - 176.9.187.218
    bind_zone_master_server_ip: 176.9.204.50
  pre_tasks:
    - name: Get dict for each zone
      include_vars:
        dir: zones
    - name: Merge zone dicts
      set_fact:
        bind_zone_domains:
          "{{ dns_nnxx_org }} +
           {{ basilicata_nnxx }} +
           {{ router_nnxx }}"

- hosts: dns-forwarder
  become: "{{ sudo | default('yes') }}"
  roles:
    - common
    - bind
  vars:
    # common
    common_ipv4_forward: 1
    common_ssh_port: 2400
    # variabili per ruolo common
    users:
      - name: michele
        authorized:
          - ./keys/michele.pub
      - name: nino
        authorized:
          - ./keys/nino.pub
      - name: marco
        authorized:
          - ./keys/hispanico.pub
      - name: federico
        authorized:
          - ./keys/federico-1.pub
          - ./keys/federico-2.pub
    # bind
    bind_listen_ipv4:
      - 127.0.0.1
      - 10.27.253.10
      - 10.27.253.11
    bind_zone_master_server_ip: 10.27.253.10
    bind_allow_recursion: any
    bind_forward_only: true
    bind_recursion: true
  pre_tasks:
    - name: Get dict for each zone
      include_vars:
        dir: zones
    - name: Merge zone dicts
      set_fact:
        bind_zone_domains:
          "{{ basilicata_nnxx }} +
           {{ router_nnxx }}"



