# roles/bind/defaults/main.yml
---

bind_log: "data/named.run"
bind_query_log: "data/query.log"

bind_other_logs:
  - name: security_file
    file: data/security.log
    versions: 3
    size: "5m"
    category: "security"
  - name: database_file
    file: data/database.log
    versions: 3
    size: "5m"
    category: "database"
  - name: security_file
    file: data/security.log
    versions: 3
    size: "5m"
    category: "security"
  - name: config_file
    file: data/config.log
    versions: 3
    size: "5m"
    category: "config"
  - name: resolver_file
    file: data/resolver.log
    versions: 3
    size: "5m"
    category: "resolver"
  - name: xfer-in_file
    file: data/xfer-in.log
    versions: 3
    size: "5m"
    category: "xfer-in"
  - name: xfer-out_file
    file: data/xfer-out.log
    versions: 3
    size: "5m"
    category: "xfer-out"
  - name: notify_file
    file: data/notify.log
    versions: 3
    size: "5m"
    category: "notify"
  - name: client_file
    file: data/client.log
    versions: 3
    size: "5m"
    category: "client"
  - name: unmatched_file
    file: data/unmatched.log
    versions: 3
    size: "5m"
    category: "unmatched"
  - name: network_file
    file: data/network.log
    versions: 3
    size: "5m"
    category: "network"
  - name: update_file
    file: data/ddns_update.log
    versions: 3
    size: "5m"
    category: "update"
  - name: dnssec_file
    file: data/dnssec.log
    versions: 3
    size: "5m"
    category: "dnssec"

#bind_zone_domains:
#  - name: "basilicata.nnxx"
#    hostmaster_email: "hostmaster"
#    networks:
#      - "10.27"

# List of acls.
bind_acls:
  - name: transfer
    match_list:
      - 10.0.0.0/8
      - 94.130.248.184/29
  - name: trusted
    match_list:
      - localhost
      - 10.0.0.0/8

# Key binding for slaves
bind_dns_keys: []
#  - name: master_key
#    algorithm: hmac-sha256
#    secret: "azertyAZERTY123456"

# List of IPv4 address of the network interface(s) to listen on. Set to "any"
# to listen on all interfaces
bind_listen_ipv4:
  - "127.0.0.1"

# List of IPv6 address of the network interface(s) to listen on.
bind_listen_ipv6:
  - "::1"

# List of hosts that are allowed to query this DNS server.
bind_allow_query:
  - "any"

# Determines whether recursion should be allowed. Typically, an authoritative
# name server should have recursion turned OFF.
bind_recursion: true
bind_allow_recursion:
  - "trusted"

# Allows BIND to be set up as a caching name server
bind_forward_only: false

# List of name servers to forward DNS requests to.
bind_forwarders:
  - "8.8.8.8"
  - "8.8.4.4"

# DNS round robin order (random or cyclic)
bind_rrset_order: "random"

# statistics channels configuration
bind_statistics_channels: true
bind_statistics_port: 8053
bind_statistics_host: 127.0.0.1
bind_statistics_allow:
  - "127.0.0.1"

# DNSSEC configuration
bind_dnssec_enable: true
bind_dnssec_validation: true

bind_extra_include_files: []

# SOA information
bind_zone_ttl: "1W"
bind_zone_time_to_refresh: "1D"
bind_zone_time_to_retry: "1H"
bind_zone_time_to_expire: "1W"
bind_zone_minimum_ttl: "1D"

# Custom location for master zone files
bind_zone_dir: "{{ bind_dir }}"
# File mode for master zone files (needs to be something like 0660 for dynamic updates)
bind_zone_file_mode: "0660"

dns_resolvconf_file: /etc/resolv.conf
dns_searches: basilicata.nnxx
dns_nameservers:
   - 127.0.0.1
   - 8.8.8.8
   - 8.8.4.4

bind_check_names: 'master ignore'
