- include: base.yml
  tags: bind

- include: keys.yml
  when: bind_role == 'master'
  tags: bind

- include: zones.yml
  tags: bind

- name: enable and start bind9
  service:
    name: bind9
    enabled: yes
    state: started
  tags: bind
