# roles/bind/tasks/master.yml
# Set up a BIND slave server
---

- name: Ensure runtime directories referenced in config exist
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ bind_owner }}"
    group: "{{ bind_group }}"
    mode: 0770
  with_items:
    - "{{ bind_dir }}/dynamic"
    - "{{ bind_dir }}/data"
    - "{{ bind_dir }}/slaves"
    - "{{ bind_zone_dir }}"
  tags: bind

- name: Slave | Main BIND config file (slave)
  template:
    src: named.conf.j2
    dest: "{{ bind_config }}"
    owner: "{{ bind_owner }}"
    group: "{{ bind_group }}"
    mode: '0640'
    setype: named_conf_t
    validate: 'named-checkconf %s'
  notify: reload bind
  tags: bind

- name: Slave | Options BIND config file (slave)
  template:
    src: slave_named.conf.options.j2
    dest: "{{ bind_config_options }}"
    owner: "{{ bind_owner }}"
    group: "{{ bind_group }}"
    mode: '0640'
    setype: named_conf_t
    validate: 'named-checkconf %s'
  notify: reload bind
  tags: bind

- name: Slave | Local BIND config file (slave)
  template:
    src: slave_named.conf.local.j2
    dest: "{{ bind_config_local }}"
    owner: "{{ bind_owner }}"
    group: "{{ bind_group }}"
    mode: '0640'
    setype: named_conf_t
    validate: 'named-checkconf %s'
  notify: reload bind
  tags: bind


- name: Slave | ensure directory for cached slaves zones
  file:
    path: "{{ bind_dir }}/slaves"
    state: directory
    owner: "{{ bind_owner }}"
    group: "{{ bind_group }}"
    mode: '0770'
    setype: named_cache_t
