# roles/bind/vars/Debian.yml
---

bind_packages:
  - python-netaddr
  - bind9
  - bind9utils
  - dnsutils
  - geoip-bin
  - geoip-database
  - geoip-database-extra

bind_service: bind9

# Main config file
bind_config: /etc/bind/named.conf
bind_config_options: /etc/bind/named.conf.options
bind_config_local: /etc/bind/named.conf.local

# Localhost zone
bind_default_zone_files:
  - /etc/bind/named.conf.default-zones

# Directory with run-time stuff
bind_dir: /var/cache/bind

bind_owner: root
bind_group: bind
