# roles/bind/vars/RedHat.yml
---

bind_packages:
  - python-netaddr
  - bind
  - bind-utils

bind_service: named

# Main config file
bind_config: /etc/named.conf
bind_config_options: /etc/named.conf.options
bind_config_local: /etc/named.conf.local

# Zone files included in the installation
bind_default_zone_files:
  - /etc/named.root.key
  - /etc/named.rfc1912.zones

# Directory with run-time stuff
bind_dir: /var/named

bind_owner: root
bind_group: named
